### ISSUE TITLE
Add support for setting a component `type` instead of a fully qualified class name

### ISSUE THREAD

**Issue by ghost** [transfer-project/bridge#13]
Example:

``` yaml
bridge:
    services:
        github:
            users:
                get:
                    type: http_api
```

Resolves to:

``` yaml
bridge:
    services:
        github:
            users:
                get:
                    class: Bridge\HttpApi\Action\HttpApiAction
```
