### ISSUE TITLE
Add support for adding custom normalizers such as mappers

### ISSUE THREAD

**Issue by ghost** [transfer-project/bridge#15]
``` yml
bridge:
  services:
    github:
      users:
        get:
          type: http_api
          options:
              mapper: ~ # resolves to normalizers=~
              normalizers: ~
```
