### ISSUE TITLE
Revise configuration

### ISSUE THREAD

**Issue by ghost** [transfer-project/bridge#16]
- [ ] 

``` yml
bridge:
  services:
    github:
      users:
        get:
          type: procedural
          options:
              sources: []
              workers: []
```

``` yml
bridge:
  services:
    github:
      users:
        get:
          type: http_api   # extends procedural
          options:
              source:  # resolves to sources:[@http_api_adapter]
                url: ~
                method: ~
                cache: 
                  adapter: ~
              normalizers: [] # resolves to workers:[*]
              encoders: [] # resolves to workers:[*]
              virtual_properties: [] # resolves to workers:[*]
              virtual_methods: [] # resolves to workers:[*]
```
- [ ] Add possibility for type specific container builders.
