### ISSUE TITLE
Review the use of type and single_type configuration keys

### ISSUE THREAD

**Issue by ghost** [transfer-project/bridge#25]
The following:

```
deserialization:
    type: 'AppBundle\Entity\Repository[]'
    single_type: 'AppBundle\Entity\Repository'
    multiple: true
```

Must be converted to:

```
deserialization:
    type: 'AppBundle\Entity\Repository[]'
```

And the following:

```
deserialization:
    type: 'AppBundle\Entity\User'
    single_type: 'AppBundle\Entity\User'
```

Must be converted to:

```
deserialization:
    type: 'AppBundle\Entity\User'
```
